import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import ThemeContextProvider from "./context/ThemeContext";
import Footer from "./components/layout/Footer";
import { PostProvider } from "./context/PostContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};








export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex flex-col min-h-screen'>
        <PostProvider>
          <ThemeContextProvider >
            <AuthProvider>
                <Navbar />
                  {children}
                <Footer />
            </AuthProvider>
          </ThemeContextProvider>
        </PostProvider>
        </body>
    </html>
  );
}
